services:
  profile-frontend:
    container_name: profile-frontend
    env_file:
      - .env
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        - VITE_BASE_URL=${VITE_BASE_URL}
    expose:
      - '3005'
    ports:
      - '3005:3005'

    